version: '2'
services:
  bot:
    build:
      context: .
      dockerfile: "docker/Dockerfile.dev"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    ports:
      - "3000:3000"
    env_file:
      - .env
    # depends_on:
    #   - postgres
    environment:
      - DB_HOST=postgres
  # postgres:
  #   image: postgres:alpine
  #   ports:
  #     - "5432:5432"
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_PASSWORD=${DB_PASS}
